# -*- coding: utf-8 -*-
"""MAIN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IzVXvWiyY4emgCLXkH7W_ZfPwmfZi0K7
"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import datasets, layers, models

(training_images, training_labels), (testing_images, testing_labels) = datasets.cifar10.load_data()
training_images, testing_images = training_images / 255, testing_images / 255

class_names = ['Plane','Car','Bird','Cat','Deer','Dog','Frog','Horse','Ship','Truck']

for i in range(16):
    plt.subplot(4,4,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.imshow(training_images[i], cmap=plt.cm.binary)
    plt.xlabel(class_names[training_labels[i][0]])

plt.show()

training_images = training_images[:20000]
training_labels = training_labels[:20000]
testing_images = testing_images[:4000]
testing_labels = testing_labels[:4000]

model = models.Sequential()
model.add(layers.Conv2D(32, (3,3), activation='relu', input_shape=(32,32,3)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.Flatten())
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(10,activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model.fit(training_images, training_labels, epochs=10, validation_data=(testing_images,testing_labels))

loss, accuracy = model.evaluate(testing_images, testing_labels)
print(f"Loss: {loss}")
print(f"Accuracy: {accuracy}")

model.save('image_classifier.keras')

"""### Making Predictions on New Images

Now that the model is trained and saved, you can use it to classify new images. The process involves loading the saved model, loading and preprocessing the new image, and then using the model's `predict` method.
"""

from tensorflow.keras.models import load_model

new_model = load_model('image_classifier.keras')
new_model.summary()

"""### Uploading a New Image for Prediction

To provide your own image, you can upload it directly to your Colab environment. Follow these steps:

1.  **Click the 'Files' icon** on the left sidebar (looks like a folder).
2.  **Click the 'Upload to session storage' icon** (looks like an upward arrow) or drag and drop your image file into the file browser.
3.  **Rename your uploaded image** to something simple, e.g., `my_image.jpg`, for easy reference in the code.

Once your image is uploaded, you can use the code below to load it, preprocess it, and make a prediction.
"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

# --- Load your uploaded image ---
# IMPORTANT: Replace 'my_image.jpg' with the actual filename of your uploaded image.
image_path = '/Car.jpg' # For example, 'my_car_photo.png'

# Load the image
img = cv.imread(image_path)

# Check if the image was loaded successfully
if img is None:
    print(f"Error: Could not load image from {image_path}. Please check the path and filename.")
else:
    # OpenCV loads images in BGR format, convert to RGB
    img = cv.cvtColor(img, cv.COLOR_BGR2RGB)

    # Resize the image to 32x32 pixels, matching the CIFAR-10 image size
    # Note: If your image is not 32x32, resizing might distort it, but it's required for the model.
    img_resized = cv.resize(img, (32, 32))

    # Normalize the pixel values to be between 0 and 1
    img_normalized = img_resized / 255.0

    # Expand dimensions to match the model's input shape (add batch dimension)
    # The model expects a batch of images, even if it's just one
    img_for_prediction = np.expand_dims(img_normalized, axis=0)

    # Display the preprocessed image
    plt.imshow(img_resized)
    plt.title(f"Uploaded and Preprocessed Image: {image_path}")
    plt.axis('off')
    plt.show()

"""Now, let's make a prediction using the loaded and preprocessed image with your trained model."""

class_names = ['Plane','Car','Bird','Cat','Deer','Dog','Frog','Horse','Ship','Truck']

# Ensure img_for_prediction was created successfully in the previous cell
if 'img_for_prediction' in locals():
    # Make a prediction
    predictions = new_model.predict(img_for_prediction)

    # Get the predicted class (the one with the highest probability)
    predicted_class_index = np.argmax(predictions[0])
    predicted_class_name = class_names[predicted_class_index]

    print(f"The model predicts this image is a: {predicted_class_name}")
    print(f"Prediction probabilities: {predictions[0]}")
else:
    print("Image for prediction was not loaded. Please ensure the previous cell ran successfully and the image path is correct.")

